import ComingSoonPanel from "./ComingSoonPanel";

// Blurred mock markdown digest preview
function MockDigestDocument() {
  return (
    <div
      style={{
        padding: "28px 32px",
        fontFamily: "var(--font-body)",
        lineHeight: "1.7",
        color: "var(--parchment)",
      }}
    >
      <p style={{ fontFamily: "var(--font-mono)", fontSize: "11px", color: "var(--fog)", marginBottom: "20px" }}>
        VENTURESCOPE WEEKLY DIGEST — Week of Nov 4, 2024
      </p>

      <h2 style={{ fontFamily: "var(--font-display)", fontSize: "22px", color: "var(--cream)", marginBottom: "4px" }}>
        Top Signal Domains This Week
      </h2>
      <p style={{ fontSize: "13px", color: "var(--fog)", marginBottom: "20px" }}>
        Ranked by combined research + product momentum across your SOUL profile.
      </p>

      {["Underwater Robotics", "AI Agents", "Climate Sensing"].map((domain, i) => (
        <div key={domain} style={{ marginBottom: "18px", paddingBottom: "18px", borderBottom: "1px solid var(--border)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "6px" }}>
            <span style={{ fontFamily: "var(--font-mono)", fontSize: "12px", color: "var(--amber)", fontWeight: "500" }}>
              #{i + 1}
            </span>
            <span style={{ fontWeight: "600", color: "var(--cream)", fontSize: "15px" }}>{domain}</span>
            <span className="vs-badge vs-badge-amber" style={{ marginLeft: "auto" }}>Score: {88 - i * 9}/100</span>
          </div>
          <p style={{ fontSize: "13px", color: "var(--parchment)" }}>
            {i + 1} new ArXiv papers, {(3 - i) * 7} GitHub repositories found. Momentum trending upward vs last week.
          </p>
        </div>
      ))}

      <p style={{ fontSize: "12px", color: "var(--fog)", fontStyle: "italic" }}>
        + 2 more domains in your full report · Generated by OpenClaw v0.9
      </p>
    </div>
  );
}

export default function WeeklyDigest() {
  return (
    <ComingSoonPanel
      icon="📋"
      title="Weekly Digest"
      description="Every Monday, OpenClaw compiles a structured digest of top signals, ranked gaps, and recommended actions — tailored entirely from your SOUL profile and delivered as a beautiful readable report."
      eta="~2 weeks"
    >
      <MockDigestDocument />
    </ComingSoonPanel>
  );
}
